# Generated by Django 3.0.2 on 2020-02-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20200205_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaimagemodel',
            name='image_file',
            field=models.FileField(upload_to='documents/image/'),
        ),
    ]
