# Generated by Django 3.0.2 on 2020-02-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20200205_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaaudiomodel',
            name='audio_file',
            field=models.FileField(upload_to='documents/audio/'),
        ),
    ]
