# Generated by Django 3.0.2 on 2020-01-13 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='news_info',
            new_name='news',
        ),
    ]
