# Generated by Django 3.0.2 on 2020-03-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200113_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image_file',
            field=models.FileField(default='ADD IMAGE', upload_to='documents/news_image/'),
        ),
    ]
