# Generated by Django 3.0.2 on 2020-02-08 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200207_1209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('user_send', 'user_get')},
        ),
    ]
