# Generated by Django 3.0.2 on 2020-02-08 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200207_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='message',
            old_name='user_get',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='user_send',
            new_name='sender',
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='message',
            name='msg_content',
        ),
        migrations.AddField(
            model_name='message',
            name='message_dataID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_data', to='accounts.MessageData'),
        ),
    ]
