# Generated by Django 3.0.2 on 2020-02-11 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200208_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagedata',
            name='title',
        ),
    ]
