# Generated by Django 3.0.2 on 2020-03-01 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_messagedata_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('sender', 'receiver')},
        ),
    ]
